### ISSUE TITLE
build base gradle structure

### ISSUE THREAD

**Issue by muratcanbur** [mertceyhan/BeerGuideApp#1]
We should build a base gradle structure.

The following blog post can be applied to the project.

 https://medium.com/mobiwise-blog/let-me-tell-you-how-you-should-build-your-gradle-structure-f13e368e00a4

**Comment by mertceyhan** [comment]
Fixed with commit c7c37628dc610de70cda0f91faa63d078f9cd189

**Comment by mertceyhan** [comment]
Fixed with commit c7c37628dc610de70cda0f91faa63d078f9cd189
